import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import ScrollToTop from "@/components/ScrollToTop";
import ScrollProgress from "@/components/ScrollProgress";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      >
        <ScrollProgress />  
        <CartProvider>
          <WishlistProvider>
            <Navbar />
            {children}
            <Footer />
             <ScrollToTop/>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
